#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
# revision: 2021121500
#
name: Moodle 3.4 - Releasing in the Plugins directory

on:
  workflow_call:
    inputs:
      plugin_name:
        required: true
        type: string
      plugin_branch:
        required: true
        type: string
      plugin_repository_url:
        required: true
        type: string
      extra_plugin_runners:
        type: string

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: true
      matrix:
        database: ['pgsql']
        moodle-branch: ['MOODLE_34_STABLE']
        php: ['7.1', '7.2']
        node: ['14.15']

    steps:
      - name: Run plugin setup
        uses: catalyst/catalyst-moodle-workflows/.github/plugin/setup@main
        with:
          extra_plugin_runners: ${{ inputs.extra_plugin_runners }}

      - name: Run plugin release
        uses: catalyst/catalyst-moodle-workflows/.github/plugin/release@main
        with:
          plugin_name: ${{ inputs.plugin_name }}
          plugin_branch: ${{ inputs.plugin_branch }}
          plugin_repository_url: ${{ inputs.plugin_repository_url }}
