#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
# revision: 2021121500
#
name: Releasing plugin group for Moodle 27 to 32 in the Plugins directory

on:
  workflow_call:
    inputs:
      plugin_name:
        required: true
        type: string
      extra_plugin_runners:
        type: string
      disable_behat:
        type: boolean
      disable_phplint:
        type: boolean
      disable_phpunit:
        type: boolean
      disable_grunt:
        type: boolean
    secrets:
      moodle_org_token:
        required: true

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Run plugin release
        uses: catalyst/catalyst-moodle-workflows/.github/plugin/release@main
        with:
          plugin_name: ${{ inputs.plugin_name }}
          moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
