name: Moodle plugin CI for Moodle master

on:
  workflow_call:
    inputs:
      extra_plugin_runners:
        type: string
      disable_behat:
        type: boolean

jobs:
  setup:
    name: CI test for Moodle master
    env:
      IGNORE_PATHS: tests/fixtures
    runs-on: 'ubuntu-latest'

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        database: ['mariadb', 'pgsql']
        moodle-branch: ['master']
        node: ['14.15']
        php: ['7.4']

    steps:
      - name: Run plugin setup
        uses: catalyst/catalyst-moodle-workflows/.github/plugin/setup@main
        with:
          extra_plugin_runners: ${{ inputs.extra_plugin_runners }}
          disable_behat: ${{ inputs.disable_behat }}
